version: "3"
services:
  nestjs-api:
    image: nest-app
    ports:
      - "3000:3000"
    networks:
      - backend-network

  graphql-gateway:
    image: gateway
    ports:
      - "4000:4000"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
